### ISSUE TITLE
Create Diffie-Hellman parameter

### ISSUE THREAD

**Issue by noplanman** [geerlingguy/ansible-role-nginx#102]
Would be great if this role would allow the option to get the dhparam generated and set up.

https://raymii.org/s/tutorials/Strong_SSL_Security_On_nginx.html#Forward_Secrecy_&_Diffie_Hellman_Ephemeral_Parameters

What I used in my role:
```yaml
- name: Generate strong DHE parameter
  command: openssl dhparam -out {{ nginx_dhparam_path }} {{ nginx_dhparam_size }}
  args:
    creates: "{{ nginx_dhparam_path }}"
```

And in the nginx.conf template I then simply add this to the `http` section:
```
ssl_dhparam {{ nginx_dhparam_path }};
```
