### ISSUE TITLE
dynamic domain using item

### ISSUE THREAD

**Issue by learnbybit** [geerlingguy/ansible-role-nginx#169]
hi im have dynamic domain, my app generate file like below
```

---
foo:
   - 1.example.com
   - 2.example.com
```

then im try make simple .yml
```

---
- hosts: test

  roles:
    - { role: geerlingguy.nginx }
  vars_files:
    - "{{ varname }}.yml"

  vars:
    nginx_use_ppa: true
    nginx_remove_default_vhost: true
   


    nginx_vhosts:
      - listen: "80"
        server_name: "{{ item }}"
        root: "/var/www/"
        index: "index.php index.html index.htm"
        state: "stop"
        return: "301 https://{{ item }}$request_uri"
        access_log: "/var/log/nginx/http.{{ item }}.access.log"
        error_log: "/var/log/nginx/http.{{ item }}.error.log"
        filename: "{{ item }}.http.conf"
        with_items: "{{ foo }}"
        when: item is defined


```
but error is item undefined.. anyone can help me ?

`FAILED! => {"msg": "'item' is undefined"}
`

**Comment by hadret** [comment]
I'm doing something similar with different role and it was a terrible idea. That being said, I don't think you can do it on `roles:` level. Here's what **may** work:

```
---
- hosts: test
  tasks:
    - name: include nginx role
      include_role:
        name: geerlingguy.nginx
      vars_files:
        - "{{ varname }}.yml"
      vars:
        nginx_use_ppa: true
        nginx_remove_default_vhost: true
        nginx_vhosts:
          - listen: "80"
            server_name: "{{ vhost }}"
            root: "/var/www/"
            index: "index.php index.html index.htm"
            state: "stop"
            return: "301 https://{{ vhost }}$request_uri"
            access_log: "/var/log/nginx/http.{{ vhost }}.access.log"
            error_log: "/var/log/nginx/http.{{ vhost }}.error.log"
            filename: "{{ vhost }}.http.conf"
      loop:
        - "{{ foo }}"
      loop_control:
        loop_var: vhost
```
