### ISSUE TITLE
No errors reported when there is an error indeed

### ISSUE THREAD

**Issue by BillHoo** [geerlingguy/ansible-role-nginx#196]
Hi geerlingguy,

Thank you for providing this role, I'm using Nginx Official Role as you mentioned but failed on this issue https://github.com/nginxinc/ansible-role-nginx/issues/238, so tried yours but still failed.

When there's an error in my site config file (the ssl certificate file does not exist at all), ansible report no errors at all until i reload nginx explicitly by command `nginx -s reload`

I don't know if you could help to fix it but wanna get some comformation from you, thank you.

```yaml
# my-role/tasks/main.yml
---
- import_role:
    name: geerlingguy.nginx
  vars:
    nginx_vhosts:
      - filename: "main-site"
        listen: "443 ssl"
        server_name: "www.abc.com"
        root: "/var/www/html"
        index: "index.html index.htm"
        extra_parameters: |
          # should report error, but it's not
          ssl_certificate     THIS_FILE_DID_NOT_EXIST.crt;
          ssl_certificate_key  THIS_FILE_DID_NOT_EXIST.key;
          ssl_protocols       TLSv1.2;
          ssl_ciphers         HIGH:!aNULL:!MD5;

# I have to reload nginx at the end by myself to make sure Ansible report the errors
#- name: "Reload Nginx"
#  command: nginx -s reload
```
