### ISSUE TITLE
[Feature Request] Ability to not manage the nginx service

### ISSUE THREAD

**Issue by Zorlin** [geerlingguy/ansible-role-nginx#210]
Hi Jeff!

I'm using the role in a project right now (thank you!) and it's working great. I need to stop it from managing the nginx service, though. In my case setting nginx_service_state: stopped is actually enough, which is cool - but - I'd love to instead have something like nginx_service_state: unmanaged.

Unfortunately, Ansible doesn't support a state=unmanaged parameter, which in a lot of ways makes sense (there are much better ways to not trigger a task!)

Two naive ways I can think of to do this, modifying the task in tasks/main.yml:

First, without having to create a new variable:
```
- name: Ensure nginx service is running as configured.
  service:
    name: nginx
    state: "{{ nginx_service_state }}"
    enabled: "{{ nginx_service_enabled }}"
  when: nginx_service_state != "unmanaged"
```

And then, something slightly less ugly:
```
- name: Ensure nginx service is running as configured.
  service:
    name: nginx
    state: "{{ nginx_service_state }}"
    enabled: "{{ nginx_service_enabled }}"
  when: not nginx_do_not_manage_service
```

May be out of scope for this role... not sure.

Let me know your thoughts :)
