### ISSUE TITLE
Redirect from http to https.

### ISSUE THREAD

**Issue by demshin** [geerlingguy/ansible-role-nginx#241]
Hello!
How can I redirect from http to https?

**Comment by wiseelf** [comment]
@demshin 
```
nginx_vhosts:
  - listen: "80"
    server_name: "my.domain.name"
    return: "301 https://$host$request_uri"
    filename: "pbot.pp.ua.80.conf"
```
