### ISSUE TITLE
How to run this role via loop @ Ansible 2.x

### ISSUE THREAD

**Issue by brutto** [geerlingguy/ansible-role-nginx#66]
Im newbie in ansivle configurations, but in readme.md file in secion about `nginx_vhosts_filename` setting i found this heplfull words `If you run the role multiple times (e.g. include the role with with_items), `. 

So i tried to separate my vhosts into different files and could not find how to do this. Any ideas?

**Comment by geerlingguy** [comment]
@brutto - If using with_items, you would need to have `nginx_vhosts_filename` different for each of the `items` you pass into the role; that way each of the times the role runs it would save a different vhosts filename and not override the last one.

Totally untested, but something like:

```yaml
  roles:
    - name: geerlingguy.nginx
      with_items:
        - nginx_vhosts_filename: my-first-vhost.conf
          [other-vars-go-here]
        - nginx_vhosts_filename: my-second-vhost.conf
          [other-vars-go-here]
```
