### ISSUE TITLE
so how does nginx gets installed on ubuntu?

### ISSUE THREAD

**Issue by babatundebusari** [geerlingguy/ansible-role-nginx#78]
```
---
- name: Add PPA for Nginx.
  apt_repository:
    repo: 'ppa:nginx/{{ nginx_ppa_version }}'
    state: present
    update_cache: yes
  register: nginx_ppa_added
  when: nginx_ppa_use

- name: Ensure nginx will reinstall if the PPA was just added.
  apt:
    name: nginx
    state: absent
  when: nginx_ppa_added.changed
```

so where does nginx gets installed???
