### ISSUE TITLE
Allow provided templates to be extended through template inheritance

### ISSUE THREAD

**Issue by oxyc** [geerlingguy/ansible-role-nginx#95]
Trellis has a convention of splitting complicated Jinja2 templates into separete blocks that can be [inherited in child templates](https://github.com/roots/trellis/tree/master/roles/sshd#customize-via-child-templates).

Eg. their nginx vhost template https://github.com/roots/trellis/blob/master/roles/wordpress-setup/templates/wordpress-site.conf.j2

Drupal VM Issue https://github.com/geerlingguy/drupal-vm/issues/1254
PR #92 (blocked by #91).

**Comment by noplanman** [comment]
I see that this has been merged, but I still have a question relating to this.

How can I override the template for each individual host?
I'm new to child templates, so maybe this is a silly question, if so, sorry!

Say I have 3 sites in my installation, how can I easily have 3 **completely different** vhost configurations for them?

The way I do it in my personal roles is something like this:
```yaml
nginx_sites:
  - name: "My Site 1"
    server_name: site1.example.com
    template: "site1.example.com.site.j2"
  - name: "My Site 2"
    server_name: site2.example.com
    template: "site2.example.com.site.j2"
  - name: "My Site 3"
    server_name: site3.example.com
    template: "site3.example.com.site.j2"
```

Being able to do something like this would be really great!

I've started using this role for a different project, putting everything in the `nginx_vhosts.extra_parameters` variable which just isn't very pretty and bloats everything.

Thanks!
