### ISSUE TITLE
Configure the target server ip or hostname in nginx_upstreams varaible.

### ISSUE THREAD

**Issue by JamesYuan** [geerlingguy/ansible-role-nginx#98]
Hi,

I define these in the group_vars/nginx/nginx.yml, but it seems the target server IP is not intercepted.

How could I write the target server IP or hostname with the port in the nginx_upstreams varaibles?

```
nginx_upstreams:
  - name: backend_front
    servers: {
      "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:8088"
    }
  
  - name: backend_manager
    servers: {
      "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:8284"
    }
  
  - name: backend_tenant_manager
    servers: {
      "hostvars[inventory_hostname]['ansible_default_ipv4']['address']"
    }
```

/etc/nginx/nginx.conf

```

    upstream backend_front {
        server {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:8088;
    }
    upstream backend_manager {
        server {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:8284;
    }
    upstream backend_tenant_manager {
        server hostvars[inventory_hostname]['ansible_default_ipv4']['address'];
    }
```

Thanks,
James.

**Comment by JamesYuan** [comment]
It works by 

```
nginx_upstreams:
  - name: backend_front
    servers:
      - "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:8088"
  
  - name: backend_manager
    servers:
      - "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:8284"
  
  - name: backend_tenant_manager
    servers:
      - "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:8282"

```
